### ISSUE TITLE
python support

### ISSUE THREAD

**Issue by ghost** [rindeal/SQLite3-Encryption#5]
hello there and thanks for this awesome project.
i just wanted to ask if there is a way to use this inside python scripts?
thanks in advance.

**Comment by rindeal** [comment]
Yes there is, since it's a drop-in replacement, it should be enough to just replace the sqlite3.dll shipped with python installation and then use `PRAGMA` statements to encrypt/decrypt databases as explained [here](https://github.com/rindeal/SQLite3-Encryption#pragmas).
